In [3]:
import numpy as np
import numpy as np
array = np.array([[[1, 2, 3], 
                      [4, 5, 6], 
                      [7, 8, 9]],

                     [[10, 11, 12], 
                      [13, 14, 15], 
                      [16, 17, 18]],

                     [[19, 20, 21], 
                      [22, 23, 24], 
                      [25, 26, 27]]])

print("3D Array:")
print(array)
     

3D Array:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [13]:
import numpy as np
array= np.array([[[1, 2, 3], 
                      [4, 5, 6], 
                      [7, 8, 9]]])
print(array.shape)
print(ndarray.flags)


(1, 3, 3)


NameError: name 'ndarray' is not defined

In [15]:
import numpy as np
A= np.ndarray( shape=2,2) , dtype=float)
print("array:", A)
print ( ndarray.flags)

SyntaxError: unmatched ')' (632598897.py, line 2)

In [26]:
import numpy as np
array= np.array([[1, 2, 3], [4, 5, 6]])



In [52]:
import numpy as np
arr1= np.array([[1, 2, 3], [4, 5, 6]])
print(arr1)
print(arr1.shape)
print(arr1.size)
print(arr1.ndim)
print(arr1.base)
print(arr1.strides)
print(arr1.nbytes)
print(arr1.real)
print(arr1.imag)
print(arr1.itemsize)
print(arr1.flags)
print(arr1.T)
print(arr1.data)

[[1 2 3]
 [4 5 6]]
(2, 3)
6
2
None
(12, 4)
24
[[1 2 3]
 [4 5 6]]
[[0 0 0]
 [0 0 0]]
4
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

[[1 4]
 [2 5]
 [3 6]]
